# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dima_pb2 as dima__pb2


class ModelEndpointStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeBirdByPhoto = channel.unary_unary(
                '/birdy_grpc.ModelEndpoint/RecognizeBirdByPhoto',
                request_serializer=dima__pb2.RecognizeBirdRequest.SerializeToString,
                response_deserializer=dima__pb2.RecognizeBirdResponse.FromString,
                )
        self.RecognizeBirdBySound = channel.unary_unary(
                '/birdy_grpc.ModelEndpoint/RecognizeBirdBySound',
                request_serializer=dima__pb2.RecognizeBirdRequest.SerializeToString,
                response_deserializer=dima__pb2.RecognizeBirdResponse.FromString,
                )


class ModelEndpointServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeBirdByPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeBirdBySound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelEndpointServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeBirdByPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeBirdByPhoto,
                    request_deserializer=dima__pb2.RecognizeBirdRequest.FromString,
                    response_serializer=dima__pb2.RecognizeBirdResponse.SerializeToString,
            ),
            'RecognizeBirdBySound': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeBirdBySound,
                    request_deserializer=dima__pb2.RecognizeBirdRequest.FromString,
                    response_serializer=dima__pb2.RecognizeBirdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'birdy_grpc.ModelEndpoint', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelEndpoint(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeBirdByPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/birdy_grpc.ModelEndpoint/RecognizeBirdByPhoto',
            dima__pb2.RecognizeBirdRequest.SerializeToString,
            dima__pb2.RecognizeBirdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeBirdBySound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/birdy_grpc.ModelEndpoint/RecognizeBirdBySound',
            dima__pb2.RecognizeBirdRequest.SerializeToString,
            dima__pb2.RecognizeBirdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
