# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dima.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dima.proto',
  package='birdy_grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndima.proto\x12\nbirdy_grpc\"$\n\x14RecognizeBirdRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\x15RecognizeBirdResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2\xcd\x01\n\rModelEndpoint\x12]\n\x14RecognizeBirdByPhoto\x12 .birdy_grpc.RecognizeBirdRequest\x1a!.birdy_grpc.RecognizeBirdResponse\"\x00\x12]\n\x14RecognizeBirdBySound\x12 .birdy_grpc.RecognizeBirdRequest\x1a!.birdy_grpc.RecognizeBirdResponse\"\x00\x62\x06proto3'
)




_RECOGNIZEBIRDREQUEST = _descriptor.Descriptor(
  name='RecognizeBirdRequest',
  full_name='birdy_grpc.RecognizeBirdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='birdy_grpc.RecognizeBirdRequest.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=62,
)


_RECOGNIZEBIRDRESPONSE = _descriptor.Descriptor(
  name='RecognizeBirdResponse',
  full_name='birdy_grpc.RecognizeBirdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='birdy_grpc.RecognizeBirdResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['RecognizeBirdRequest'] = _RECOGNIZEBIRDREQUEST
DESCRIPTOR.message_types_by_name['RecognizeBirdResponse'] = _RECOGNIZEBIRDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognizeBirdRequest = _reflection.GeneratedProtocolMessageType('RecognizeBirdRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEBIRDREQUEST,
  '__module__' : 'dima_pb2'
  # @@protoc_insertion_point(class_scope:birdy_grpc.RecognizeBirdRequest)
  })
_sym_db.RegisterMessage(RecognizeBirdRequest)

RecognizeBirdResponse = _reflection.GeneratedProtocolMessageType('RecognizeBirdResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEBIRDRESPONSE,
  '__module__' : 'dima_pb2'
  # @@protoc_insertion_point(class_scope:birdy_grpc.RecognizeBirdResponse)
  })
_sym_db.RegisterMessage(RecognizeBirdResponse)



_MODELENDPOINT = _descriptor.ServiceDescriptor(
  name='ModelEndpoint',
  full_name='birdy_grpc.ModelEndpoint',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeBirdByPhoto',
    full_name='birdy_grpc.ModelEndpoint.RecognizeBirdByPhoto',
    index=0,
    containing_service=None,
    input_type=_RECOGNIZEBIRDREQUEST,
    output_type=_RECOGNIZEBIRDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecognizeBirdBySound',
    full_name='birdy_grpc.ModelEndpoint.RecognizeBirdBySound',
    index=1,
    containing_service=None,
    input_type=_RECOGNIZEBIRDREQUEST,
    output_type=_RECOGNIZEBIRDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELENDPOINT)

DESCRIPTOR.services_by_name['ModelEndpoint'] = _MODELENDPOINT

# @@protoc_insertion_point(module_scope)
